spring.application.name=coreservices

server.port=8081

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d8nptbmrnols73e24meg-a.oregon-postgres.render.com:5432/mth_zxdu 
spring.datasource.username=postgres_mth
spring.datasource.password=Zaj0slpGroHfUkgLXqtlRNSHTMuuHYrp

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true